name: mono
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  loading_indicator: ^3.1.1  
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  http: ^1.5.0
  flutter_svg: ^2.2.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  shimmer: ^3.0.0
  share_plus: ^11.1.0
  fl_chart: ^1.0.0


flutter_launcher_icons:   
  android: true
  
  image_path: "assets/images/wallet_with_cash.png"



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/


